
window.phoneAppManager && window.phoneAppManager.register('dealer', {
    wrapper:null, data:{categories:[],vehicles:[]}, category:'all', selected:null,
    getHTML(){return '<div class="vdapp"><div class="vd-shell"><div class="vd-top"><div><div class="vd-title">Genesis Motors</div><div class="vd-sub">Catalogue du concessionnaire</div></div><div class="vd-pill">Consultation uniquement</div></div><div class="vd-body"><div class="vd-side"><div id="vd-cats" class="vd-cats"></div><div id="vd-list" class="vd-list"></div></div><div id="vd-detail" class="vd-detail"></div></div></div></div>';},
    onOpen(wrapper){this.wrapper=wrapper; this._h=this._onData.bind(this); WLCBridge.on('vdCatalogList', this._h); this._loading(); WLCBridge.send('vdListCatalog',{});},
    onClose(){if(this._h) WLCBridge.off('vdCatalogList', this._h); this.wrapper=null;},
    _loading(){var l=this.wrapper.querySelector('#vd-list'), d=this.wrapper.querySelector('#vd-detail'); if(l) l.innerHTML='<div class="vd-loading">Chargement du catalogue...</div>'; if(d) d.innerHTML='';},
    _onData(msg){this.data=(msg&&msg.data)||{categories:[],vehicles:[]}; if(!this.selected && this.data.vehicles && this.data.vehicles[0]) this.selected=this.data.vehicles[0].id; this._render();},
    _fmt(n){n=parseInt(n)||0; return n.toString().replace(/\B(?=(\d{3})+(?!\d))/g,' ')+' $';},
    _esc(s){if(!s) return ''; var d=document.createElement('div'); d.textContent=s; return d.innerHTML;},
    _vehicles(){var v=(this.data.vehicles||[]).slice(); if(this.category!=='all') v=v.filter(x=>x.category===this.category); return v;},
    _render(){var cats=this.wrapper.querySelector('#vd-cats'), list=this.wrapper.querySelector('#vd-list'); var self=this; cats.innerHTML='<button class="'+(this.category==='all'?'active':'')+'" data-cat="all">Tout</button>' + (this.data.categories||[]).map(function(c){return '<button class="'+(self.category===c.id?'active':'')+'" data-cat="'+self._esc(c.id)+'">'+self._esc(c.name)+'</button>';}).join(''); cats.querySelectorAll('button').forEach(function(b){b.onclick=function(){self.category=b.dataset.cat; var items=self._vehicles(); self.selected=items[0]&&items[0].id||null; self._render();};}); var items=this._vehicles(); if(!items.length){ list.innerHTML='<div class="vd-loading">Aucun véhicule dans cette catégorie.</div>'; this._renderDetail(null); return; } list.innerHTML=items.map(function(v){ return '<div class="vd-card '+(self.selected===v.id?'active':'')+'" data-id="'+self._esc(v.id)+'"><div class="vd-card-top"><div class="vd-avatar">'+self._esc((v.name||'?').charAt(0))+'</div><div class="vd-card-meta"><div class="vd-name">'+self._esc(v.name)+'</div><div class="vd-cat">'+self._esc(v.category)+'</div></div><div class="vd-price">'+self._fmt(v.priceTTC)+'</div></div><div class="vd-desc">'+self._esc(v.description||'Aucune description')+'</div></div>'; }).join(''); list.querySelectorAll('.vd-card').forEach(function(c){ c.onclick=function(){self.selected=c.dataset.id; self._render();}; }); var current=items.find(v=>v.id===this.selected)||items[0]; this._renderDetail(current);},
    _renderDetail(v){ var el=this.wrapper.querySelector('#vd-detail'); if(!el) return; if(!v){ el.innerHTML=''; return; } el.innerHTML='<div class="vd-preview"><div class="vd-preview-hero"><div class="vd-preview-badge">'+this._esc(v.category||'vehicle')+'</div><div class="vd-preview-name">'+this._esc(v.name||'Vehicle')+'</div><div class="vd-preview-model">'+this._esc(v.class||'Unknown class')+'</div></div><div class="vd-specs"><div><span>Prix HT</span><strong>'+this._fmt(v.priceHT)+'</strong></div><div><span>Taxe</span><strong>'+this._fmt(v.priceTax)+'</strong></div><div><span>Prix TTC</span><strong>'+this._fmt(v.priceTTC)+'</strong></div></div><div class="vd-lore">'+this._esc(v.description||'Aucune description fournie.')+'</div><div class="vd-note">Le téléphone affiche le catalogue et les prix. L’achat reste uniquement disponible au concessionnaire.</div></div>'; }
});
