
window.phoneAppManager && window.phoneAppManager.register('realestate', {
    wrapper:null, data:{properties:[]}, filter:'all', sort:'price_asc',
    getHTML(){return '<div class="gh-app"><div class="gh-shell"><div class="gh-top"><div><div class="gh-title">Genesis Homes</div><div class="gh-sub">Propriétés actuellement proposées</div></div><div class="gh-badge">Consultation uniquement</div></div><div class="gh-controls"><select id="gh-filter"><option value="all">Toutes</option><option value="garage">Avec garage</option><option value="basement">Avec cave</option></select><select id="gh-sort"><option value="price_asc">Prix croissant</option><option value="price_desc">Prix décroissant</option><option value="slots_desc">Stockage décroissant</option></select></div><div id="gh-list" class="gh-list"></div></div></div>';},
    onOpen(wrapper){this.wrapper=wrapper; this._h=this._onList.bind(this); WLCBridge.on('ghPropertiesList', this._h); this._bindControls(); this._loading(); WLCBridge.send('ghListProperties',{});},
    onClose(){ if(this._h) WLCBridge.off('ghPropertiesList', this._h); this.wrapper=null; },
    _bindControls(){ var self=this; setTimeout(function(){ var f=self.wrapper.querySelector('#gh-filter'), s=self.wrapper.querySelector('#gh-sort'); if(f) f.onchange=function(){self.filter=f.value; self._render();}; if(s) s.onchange=function(){self.sort=s.value; self._render();}; },0); },
    _loading(){var el=this.wrapper&&this.wrapper.querySelector('#gh-list'); if(el) el.innerHTML='<div class="gh-loading"><div class="gh-spinner"></div><div>Synchronisation avec le registre immobilier...</div></div>';},
    _onList(msg){ this.data=(msg&&msg.data)||{properties:[]}; this._render(); },
    _fmt(n){n=parseInt(n)||0; return n.toString().replace(/\B(?=(\d{3})+(?!\d))/g,' ')+ ' $';},
    _esc(s){ if(!s) return ''; var d=document.createElement('div'); d.textContent=s; return d.innerHTML; },
    _items(){ var arr=(this.data.properties||[]).slice(); if(this.filter==='garage') arr=arr.filter(p=>p.hasGarage); else if(this.filter==='basement') arr=arr.filter(p=>p.hasBasement); if(this.sort==='price_desc') arr.sort((a,b)=>b.purchasePrice-a.purchasePrice); else if(this.sort==='slots_desc') arr.sort((a,b)=>(b.storageSlots*b.storageCount)-(a.storageSlots*a.storageCount)); else arr.sort((a,b)=>a.purchasePrice-b.purchasePrice); return arr; },
    _render(){ var el=this.wrapper&&this.wrapper.querySelector('#gh-list'); if(!el) return; var items=this._items(); if(!items.length){ el.innerHTML='<div class="gh-empty">Aucune propriété en vente actuellement.</div>'; return; } el.innerHTML=items.map((p)=>{ var addr=[p.address&&p.address.number?('#'+p.address.number):'', p.address&&p.address.street?p.address.street:'', p.address&&p.address.city?p.address.city:''].filter(Boolean).join(' '); var storage=(parseInt(p.storageCount)||0) > 0 ? ((p.storageCount||0)+' inventaire(s) · '+(p.storageSlots||0)+' slots') : 'Aucun stockage'; var mode='Achat'; if(p.buyableMode===1) mode='Achat / Location'; else if(p.buyableMode===3) mode='Location uniquement'; return '<div class="gh-card"><div class="gh-hero"><div class="gh-icon">🏠</div><div class="gh-meta"><div class="gh-name">'+this._esc(p.name||'Property')+'</div><div class="gh-type">'+this._esc(p.habitationType||'Property')+'</div><div class="gh-address">'+this._esc(addr||'Adresse non renseignée')+'</div></div><div class="gh-price">'+this._fmt(p.purchasePrice)+'</div></div><div class="gh-tags"><span>'+this._esc(mode)+'</span>'+(p.hasGarage?'<span>Garage</span>':'')+(p.hasBasement?'<span>Cave</span>':'')+'</div><div class="gh-desc">'+this._esc(p.desc||'Aucune description fournie.')+'</div><div class="gh-footer"><div>Stockage: '+this._esc(storage)+'</div><div>Loyer: '+this._fmt(p.rentPrice)+'</div></div></div>'; }).join(''); }
});
