
window.phoneAppManager && window.phoneAppManager.register('mailbox', {
    wrapper:null, mails:[], selected:null,
    getHTML(){return '<div class="mb-app"><div class="mb-shell"><div class="mb-top"><div><div class="mb-title">Boîte mail</div><div class="mb-sub">Documents et confirmations d\'achat</div></div><button id="mb-refresh" class="mb-refresh">Actualiser</button></div><div class="mb-body"><div id="mb-list" class="mb-list"></div><div id="mb-view" class="mb-view"></div></div></div></div>';},
    onOpen(wrapper){this.wrapper=wrapper; this._lh=this._onList.bind(this); this._mh=this._onMark.bind(this); this._dh=this._onDownload.bind(this); this._ph=this._onPush.bind(this); WLCBridge.on('mailList', this._lh); WLCBridge.on('mailMarkReadResult', this._mh); WLCBridge.on('mailDownloadResult', this._dh); WLCBridge.on('mailPush', this._ph); wrapper.querySelector('#mb-refresh').onclick=()=>this._reload(); this._reload();},
    onClose(){['mailList','mailMarkReadResult','mailDownloadResult','mailPush'].forEach(n=>WLCBridge.off(n)); this.wrapper=null;},
    _reload(){var l=this.wrapper&&this.wrapper.querySelector('#mb-list'); var v=this.wrapper&&this.wrapper.querySelector('#mb-view'); if(l) l.innerHTML='<div class="mb-loading">Synchronisation des emails...</div>'; if(v) v.innerHTML=''; WLCBridge.send('mailList',{});},
    _onList(msg){ var d=(msg&&msg.data)||{}; this.mails=d.mails||[]; if(!this.selected && this.mails[0]) this.selected=this.mails[0].id; this._render(); },
    _onPush(msg){ if(window.phoneNotifications && msg && msg.data){ var d=msg.data; window.phoneNotifications.show('Mail', (d.subject||'Nouveau mail'), 'apps/mailbox/icon.png'); } this._reload(); },
    _onMark(){},
    _onDownload(msg){ var d=msg&&msg.data; if(window.phoneNotifications){ window.phoneNotifications.show('Mail', d&&d.success ? 'Pièce jointe téléchargée' : 'Échec du téléchargement', 'apps/mailbox/icon.png'); } },
    _esc(s){if(!s) return ''; var d=document.createElement('div'); d.textContent=s; return d.innerHTML;},
    _render(){ var list=this.wrapper.querySelector('#mb-list'); if(!this.mails.length){ list.innerHTML='<div class="mb-loading">Aucun email.</div>'; this.wrapper.querySelector('#mb-view').innerHTML=''; return; } var self=this; list.innerHTML=this.mails.map(function(m){ return '<div class="mb-item '+(self.selected===m.id?'active':'')+' '+(!m.isRead?'unread':'')+'" data-id="'+m.id+'"><div class="mb-item-top"><div class="mb-sender">'+self._esc(m.sender||'Genesis')+'</div><div class="mb-date">'+self._esc(m.createdAt||'')+'</div></div><div class="mb-subject">'+self._esc(m.subject||'Sans objet')+'</div><div class="mb-preview">'+self._esc((m.body||'').slice(0,92))+'</div></div>'; }).join(''); list.querySelectorAll('.mb-item').forEach(function(it){ it.onclick=function(){ self.selected=parseInt(it.dataset.id); self._renderView(); }; }); this._renderView(); },
    _renderView(){ var view=this.wrapper.querySelector('#mb-view'); var m=this.mails.find(x=>x.id===this.selected) || this.mails[0]; if(!m){view.innerHTML=''; return;} this.selected=m.id; if(!m.isRead){ m.isRead=true; WLCBridge.send('mailMarkRead',{id:m.id}); } var attachments=m.attachments||[]; view.innerHTML='<div class="mb-head"><div class="mb-head-top"><div><div class="mb-view-subject">'+this._esc(m.subject||'Sans objet')+'</div><div class="mb-from">De '+this._esc(m.sender||'Genesis')+' · '+this._esc(m.createdAt||'')+'</div></div><div class="mb-chip '+this._esc(m.category||'general')+'">'+this._esc(m.category||'general')+'</div></div></div><div class="mb-message">'+this._esc(m.body||'').replace(/\n/g,'<br>')+'</div><div class="mb-att-title">Pièces jointes</div><div class="mb-att-list">'+(attachments.length?attachments.map((a,i)=>'<div class="mb-att"><div class="mb-att-left"><div class="mb-att-icon">'+(a.kind==='vehicle_document'?'🚗':'🏠')+'</div><div><div class="mb-att-name">'+this._esc(a.name||'Document')+'</div><div class="mb-att-meta">'+this._esc(a.doc_type||a.kind||'attachment')+'</div></div></div><div class="mb-att-actions"><button class="mb-preview-btn" data-idx="'+i+'">Voir</button><button class="mb-download-btn" data-idx="'+i+'">Télécharger</button></div></div>').join(''):'<div class="mb-noatt">Aucune pièce jointe.</div>')+'</div><div id="mb-attachment-preview"></div>'; var self=this; view.querySelectorAll('.mb-download-btn').forEach(function(b){ b.onclick=function(){ WLCBridge.send('mailDownload',{mailId:m.id,index:parseInt(b.dataset.idx)}); }; }); view.querySelectorAll('.mb-preview-btn').forEach(function(b){ b.onclick=function(){ self._renderAttachmentPreview(attachments[parseInt(b.dataset.idx)]); }; }); },
    _renderAttachmentPreview(att){ var el=this.wrapper.querySelector('#mb-attachment-preview'); if(!el) return; if(!att){ el.innerHTML=''; return; } var meta=att.metadata||{}; var rows=''; Object.keys(meta).slice(0,12).forEach(function(k){ if(k==='strokes') return; rows += '<div class="mb-p-row"><span>'+k+'</span><strong>'+String(meta[k])+'</strong></div>'; }); el.innerHTML='<div class="mb-preview-card"><div class="mb-preview-head">'+this._esc(att.name||'Document')+'</div><div class="mb-preview-type">'+this._esc(att.doc_type||att.kind||'document')+'</div><div class="mb-preview-grid">'+rows+'</div></div>'; }
});
